import { PlanState } from "./plan-markdown";
import { QueryResultRow } from "../utils/db";
import { groupByDateWindow } from "./helpers";

export function renderFlightReport(
  plan: PlanState,
  rows: QueryResultRow[]
): string {
  const lines: string[] = [];
  const start = plan.routes[0].origin;
  const end = plan.routes[0].destination;

  lines.push(`# Trip Report: ${start} → ${end}`);
  lines.push("");
  lines.push("## Summary");
  lines.push("");
  lines.push(`- **Travellers:** ${plan.constraints.adults} adults${plan.constraints.children.length ? `, children: [${plan.constraints.children.join(", ")}]` : ""}`);
  if (plan.constraints.min_days) lines.push(`- **Dates:** ${plan.months.join(", ")}, ${plan.constraints.min_days}-${plan.constraints.max_days} nights`);
  lines.push(`- **Transport:** Flight`);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Found Options");

  const groups = groupByDateWindow(rows);
  let i = 1;
  const keys = Object.keys(groups).sort();
  for (const key of keys) {
    lines.push("");
    lines.push(`### 🗓️ Option ${i}: ${key}`);
    lines.push("");
    groups[key].forEach((t, idx) => {
      const time = `${t.out_dep_time}–${t.out_arr_time}${t.ret_dep_time ? ` ↔ ${t.ret_dep_time}–${t.ret_arr_time}` : ""}`;
      lines.push(`${idx + 1}. **${t.airline}** — ${time}`);
      lines.push(`   - **Precio:** €${t.total_price} | **Escalas:** ${t.out_stops}`);
    });
    if (groups[key][0]?.search_url) {
      lines.push("");
      lines.push(`🔗 [View on Kayak](${groups[key][0].search_url})`);
    }
    lines.push("");
    lines.push("---");
    i++;
  }

  lines.push("");
  lines.push("---");
  lines.push(`_Report generated by OpenClaw on ${new Date().toISOString().split('T')[0]}_`);

  return lines.join("\n");
}
